name: Build & test
on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    name: Build and execute unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Unit test execution & coverage computation
        run: npm run unit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}